# Generated by Django 3.0.1 on 2019-12-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(null=True)),
                ('vote_open', models.DateTimeField(null=True)),
                ('vote_closed', models.DateTimeField(null=True)),
                ('finalized_log', models.CharField(blank=True, max_length=255, null=True)),
                ('open_for', models.ManyToManyField(blank=True, help_text='Override open and close times for specific users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('text_answer', models.CharField(blank=True, help_text='Correct answer for fill in the blank.', max_length=255, null=True)),
                ('points', models.FloatField(default=1, help_text='How many points is this worth?')),
                ('correct_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrestleleague.Answer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_questions', to='wrestleleague.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(blank=True, max_length=128, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('points_awarded', models.FloatField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrestleleague.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrestleleague.MatchQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrestleleague.Promotion'),
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrestleleague.Season'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wrestleleague.MatchQuestion'),
        ),
    ]
