# Generated by Django 3.0.1 on 2019-12-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrestleleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrestleleague.Answer'),
        ),
    ]
