# Generated by Django 3.0.1 on 2019-12-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestleleague', '0002_auto_20191228_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
