# Generated by Django 3.0.1 on 2020-01-03 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wrestleleague', '0003_season_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='added_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 1, 3, 23, 27, 30, 297675, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
